package bxm.dft.smp.online.service;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import bxm.dft.app.DefaultApplicationException;
import bxm.common.annotaion.BxmCategory;
import bxm.dft.context.DefaultApplicationContext;
import bxm.container.annotation.BxmService;
import bxm.container.annotation.BxmServiceOperation;
import bxm.dft.smp.online.bean.MSmpEmpInfMng;
import bxm.dft.smp.online.bean.MSmpEmpInfMng01;
import bxm.dft.smp.online.dbio.dto.DSmpEmpTst000Dto;
import bxm.dft.smp.online.service.dto.SSMP1002A001InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A001OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A001OutDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A002InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A002OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A002OutDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A011InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A011InDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A011OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A012InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A012InDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A012OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A021InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A021InDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A021OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A022InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A022InDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A022OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A023InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A023OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A031InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A031InDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A031OutDto;
import bxm.dft.smp.online.service.dto.SSMP1002A032InDto;
import bxm.dft.smp.online.service.dto.SSMP1002A032InDtoSubGrid01;
import bxm.dft.smp.online.service.dto.SSMP1002A032OutDto;

/**
 * <b>BXM Service class</b>
 * <p>
 * <b>Revision history</b><br>
 * <pre>
 * 2017.11.14 : New creation
 * </pre>
 *
 * @since 2017.11.14
 * @version 1.0.0
 * @author Education
 */
@BxmService("SSMP1002A")
@BxmCategory(logicalName = "Multi CRUD", description = "Multi CRUD")
public class SSMP1002A {
	final Logger logger = LoggerFactory.getLogger(this.getClass());

	private MSmpEmpInfMng mSmpEmpInfMng;
	private MSmpEmpInfMng01 mSmpEmpInfMng01;

	@BxmServiceOperation("ssmp1002a001")
	@BxmCategory(logicalName = "Multi select 1", description = "Multi select 1")
	public SSMP1002A001OutDto ssmp1002a001(SSMP1002A001InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng01 = DefaultApplicationContext.getBean(mSmpEmpInfMng01, MSmpEmpInfMng01.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A001OutDto output = new SSMP1002A001OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A001OutDtoSubGrid01 outDtoSub1 = null;
		
		/**
		 * @BXMType VariableDeclaration
		 */
		List<DSmpEmpTst000Dto> beanOutput = null;

		/**
		 * @BXMType IF
		 * @Desc validate input data
		 */
		if (input.getFeduEmpNm() == null || input.getFeduEmpNm().isEmpty()) {
			throw new DefaultApplicationException("BXME60004", new Object[]{});
		}

		/**
		 * @BXMType VariableDeclaration
		 */
		DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
		
		/**
		 * @BXMType LogicalArea
		 * @Desc DTO mapping
		 */
		{
			beanInput.setFeduEmpNm(input.getFeduEmpNm());
		}

		/**
		 * @BXMType BeanCall
		 * @Desc Call bean method to select employee information
		 */
		beanOutput = mSmpEmpInfMng01.getEmpListbyNm(beanInput);

		/**
		 * @BXMType LogicalArea
		 * @Desc DTO mapping
		 */
		{
			output.setGrid01_COUNT(beanOutput.size());
		}

		/**
		 * @BXMType Loop
		 * @Desc Mapping bean outputs to service output
		 */
		for (DSmpEmpTst000Dto fetchDto : beanOutput) {
			outDtoSub1 = new SSMP1002A001OutDtoSubGrid01();

			// Generated by code generator [[
			outDtoSub1.setFeduEmpNo(fetchDto.getFeduEmpNo());
			outDtoSub1.setFeduEmpNm(fetchDto.getFeduEmpNm());
			outDtoSub1.setFeduOccpNm(fetchDto.getFeduOccpNm());
			outDtoSub1.setFeduMngrEmpNo(fetchDto.getFeduMngrEmpNo());
			outDtoSub1.setFeduIpsaDt(fetchDto.getFeduIpsaDt());
			outDtoSub1.setFeduPayAmt(fetchDto.getFeduPayAmt());
			outDtoSub1.setFeduDeptNo(fetchDto.getFeduDeptNo());
			// Generated by code generator ]]

			output.getGrid01().add(outDtoSub1);
		}

		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}

		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a002")
	@BxmCategory(logicalName = "Multi select 2", description = "Multi select 2")
	public SSMP1002A002OutDto ssmp1002a002(SSMP1002A002InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng01 = DefaultApplicationContext.getBean(mSmpEmpInfMng01, MSmpEmpInfMng01.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A002OutDto output = new SSMP1002A002OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A002OutDtoSubGrid01 outDtoSub1 = null;
		
		/**
		 * @BXMType VariableDeclaration
		 */
		List<DSmpEmpTst000Dto> beanOutput = null;

		/**
		 * @BXMType IF
		 * @Desc validate input data
		 */
		if (input.getFeduEmpNm() == null || input.getFeduEmpNm().isEmpty()) {
			throw new DefaultApplicationException("BXME60004", new Object[]{});
		}

		/**
		 * @BXMType BeanCall
		 * @Desc Call bean method to select employee information
		 */
		beanOutput = mSmpEmpInfMng01.getEmpList(input);
		
		/**
		 * @BXMType LogicalArea
		 * @Desc DTO mapping
		 */
		{
			output.setGrid01_COUNT(beanOutput.size());
		}

		/**
		 * @BXMType Loop
		 * @Desc Mapping bean outputs to service output
		 */
		for (DSmpEmpTst000Dto fetchDto : beanOutput) {
			outDtoSub1 = new SSMP1002A002OutDtoSubGrid01();

			// Generated by code generator [[
			outDtoSub1.setFeduEmpNo(fetchDto.getFeduEmpNo());
			outDtoSub1.setFeduEmpNm(fetchDto.getFeduEmpNm());
			outDtoSub1.setFeduOccpNm(fetchDto.getFeduOccpNm());
			outDtoSub1.setFeduMngrEmpNo(fetchDto.getFeduMngrEmpNo());
			outDtoSub1.setFeduIpsaDt(fetchDto.getFeduIpsaDt());
			outDtoSub1.setFeduPayAmt(fetchDto.getFeduPayAmt());
			outDtoSub1.setFeduDeptNo(fetchDto.getFeduDeptNo());
			// Generated by code generator ]]

			output.getGrid01().add(outDtoSub1);
		}

		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}

		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a011")
	@BxmCategory(logicalName = "Multi insert 1", description = "Multi insert 1")
	public SSMP1002A011OutDto ssmp1002a011(SSMP1002A011InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng = DefaultApplicationContext.getBean(mSmpEmpInfMng, MSmpEmpInfMng.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A011OutDto output = new SSMP1002A011OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		int addCnt = 0;
	
		/**
		 * @BXMType Loop
		 * @Desc Input dto mapping and insert employee data
		 */
		for (SSMP1002A011InDtoSubGrid01 subGrid01 : input.getGrid01()) {

			DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
			// Generated by code generator [[
			beanInput.setFeduEmpNo(subGrid01.getFeduEmpNo());
			beanInput.setFeduEmpNm(subGrid01.getFeduEmpNm());
			beanInput.setFeduOccpNm(subGrid01.getFeduOccpNm());
			beanInput.setFeduMngrEmpNo(subGrid01.getFeduMngrEmpNo());
			beanInput.setFeduIpsaDt(subGrid01.getFeduIpsaDt());
			beanInput.setFeduPayAmt(subGrid01.getFeduPayAmt());
			beanInput.setFeduDeptNo(subGrid01.getFeduDeptNo());
			// Generated by code generator ]]
			
			/**
			 * @BXMType BeanCall
			 * @Desc Call bean method to insert employe data
			 */
			addCnt += mSmpEmpInfMng.addEmpInf(beanInput);
		}
		logger.debug("addCnt : {}", addCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}

		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}

		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}


	@BxmServiceOperation("ssmp1002a012")
	@BxmCategory(logicalName = "Multi insert 2", description = "Multi insert 2")
	public SSMP1002A012OutDto ssmp1002a012(SSMP1002A012InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);


		mSmpEmpInfMng01 = DefaultApplicationContext.getBean(mSmpEmpInfMng01, MSmpEmpInfMng01.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A012OutDto output = new SSMP1002A012OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		List<DSmpEmpTst000Dto> beanInputs = new ArrayList<DSmpEmpTst000Dto>();

		/**
		 * @BXMType Loop
		 * @Desc mapping input data dto
		 */
		for (SSMP1002A012InDtoSubGrid01 subGrid01 : input.getGrid01()) {

			DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
			// Generated by code generator [[
			beanInput.setFeduEmpNo(subGrid01.getFeduEmpNo());
			beanInput.setFeduEmpNm(subGrid01.getFeduEmpNm());
			beanInput.setFeduOccpNm(subGrid01.getFeduOccpNm());
			beanInput.setFeduMngrEmpNo(subGrid01.getFeduMngrEmpNo());
			beanInput.setFeduIpsaDt(subGrid01.getFeduIpsaDt());
			beanInput.setFeduPayAmt(subGrid01.getFeduPayAmt());
			beanInput.setFeduDeptNo(subGrid01.getFeduDeptNo());
			// Generated by code generator ]]

			beanInputs.add(beanInput);
		}

		/**
		 * @BXMType BeanCall
		 * @Desc call bean method to insert data
		 */
		int addCnt = mSmpEmpInfMng01.addEmpInfList(beanInputs);
		logger.debug("addCnt : {}", addCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}
		
		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}


		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a021")
	@BxmCategory(logicalName = "Multi update 1", description = "Multi update 1")
	public SSMP1002A021OutDto ssmp1002a021(SSMP1002A021InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng = DefaultApplicationContext.getBean(mSmpEmpInfMng, MSmpEmpInfMng.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A021OutDto output = new SSMP1002A021OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		int modifyCnt = 0;
		
		/**
		 * @BXMType Loop
		 * @Desc mapping input data and update employee data
		 */
		for (SSMP1002A021InDtoSubGrid01 subGrid01 : input.getGrid01()) {

			DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
			// Generated by code generator [[
			beanInput.setFeduEmpNo(subGrid01.getFeduEmpNo());
			beanInput.setFeduEmpNm(subGrid01.getFeduEmpNm());
			beanInput.setFeduOccpNm(subGrid01.getFeduOccpNm());
			beanInput.setFeduMngrEmpNo(subGrid01.getFeduMngrEmpNo());
			beanInput.setFeduIpsaDt(subGrid01.getFeduIpsaDt());
			beanInput.setFeduPayAmt(subGrid01.getFeduPayAmt());
			beanInput.setFeduDeptNo(subGrid01.getFeduDeptNo());
			// Generated by code generator ]]
			/**
			 * @BXMType BeanCall
			 * @Desc Call bean method to update employee information
			 */
			modifyCnt += mSmpEmpInfMng.modifyEmpInf(beanInput);
		}
		logger.debug("modifyCnt : {}", modifyCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}
		
		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}

		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a022")
	@BxmCategory(logicalName = "Multi update 2", description = "Multi update 2")
	public SSMP1002A022OutDto ssmp1002a022(SSMP1002A022InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng01 = DefaultApplicationContext.getBean(mSmpEmpInfMng01, MSmpEmpInfMng01.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A022OutDto output = new SSMP1002A022OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		List<DSmpEmpTst000Dto> beanInputs = new ArrayList<DSmpEmpTst000Dto>();

		/**
		 * @BXMType Loop
		 * @Desc mapping input data dto
		 */
		for (SSMP1002A022InDtoSubGrid01 subGrid01 : input.getGrid01()) {

			DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
			// Generated by code generator [[
			beanInput.setFeduEmpNo(subGrid01.getFeduEmpNo());
			beanInput.setFeduEmpNm(subGrid01.getFeduEmpNm());
			beanInput.setFeduOccpNm(subGrid01.getFeduOccpNm());
			beanInput.setFeduMngrEmpNo(subGrid01.getFeduMngrEmpNo());
			beanInput.setFeduIpsaDt(subGrid01.getFeduIpsaDt());
			beanInput.setFeduPayAmt(subGrid01.getFeduPayAmt());
			beanInput.setFeduDeptNo(subGrid01.getFeduDeptNo());
			// Generated by code generator ]]
			beanInputs.add(beanInput);
		}

		/**
		 * @BXMType BeanCall
		 * @Desc Call bean method to update employee informations
		 */
		int addCnt = mSmpEmpInfMng01.modifyEmpInfBySelectOneLock(beanInputs);
		logger.debug("addCnt : {}", addCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}

		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}


		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a023")
	@BxmCategory(logicalName = "Multi update 3", description = "Multi update 3")
	public SSMP1002A023OutDto ssmp1002a023(SSMP1002A023InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);


		mSmpEmpInfMng01 = DefaultApplicationContext.getBean(mSmpEmpInfMng01, MSmpEmpInfMng01.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A023OutDto output = new SSMP1002A023OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();

		/**
		 * @BXMType LogicalArea
		 * @Desc DTO mapping
		 */
		{
			// Generated by code generator [[
			beanInput.setFeduEmpNo(input.getFeduEmpNo());
			beanInput.setFeduEmpNm(input.getFeduEmpNm());
			beanInput.setFeduOccpNm(input.getFeduOccpNm());
			beanInput.setFeduMngrEmpNo(input.getFeduMngrEmpNo());
			beanInput.setFeduIpsaDt(input.getFeduIpsaDt());
			beanInput.setFeduPayAmt(input.getFeduPayAmt());
			beanInput.setFeduDeptNo(input.getFeduDeptNo());
		}

		/**
		 * @BXMType BeanCall
		 * @Desc Call bean method to update employee information
		 */
		int addCnt = mSmpEmpInfMng01.modifyEmpInfBySelectListLock(beanInput);
		logger.debug("addCnt : {}", addCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}

		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}

		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a031")
	@BxmCategory(logicalName = "Multi delete 1", description = "Multi delete 1")
	public SSMP1002A031OutDto ssmp1002a031(SSMP1002A031InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng = DefaultApplicationContext.getBean(mSmpEmpInfMng, MSmpEmpInfMng.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A031OutDto output = new SSMP1002A031OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		int removeCnt = 0;
		
		/**
		 * @BXMType Loop
		 * @Desc Mapping input data and delete employe information
		 */
		for (SSMP1002A031InDtoSubGrid01 subGrid01 : input.getGrid01()) {

			DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
			// Generated by code generator [[
			beanInput.setFeduEmpNo(subGrid01.getFeduEmpNo());

			// Generated by code generator ]]
			/**
			 * @BXMType BeanCall
			 * @Desc Call bean method to delete employee information
			 */
			removeCnt += mSmpEmpInfMng.removeEmpInf(beanInput);
		}

		logger.debug("removeCnt : {}", removeCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}
		
		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}

		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

	@BxmServiceOperation("ssmp1002a032")
	@BxmCategory(logicalName = "Multi delete 2", description = "Multi delete 2")
	public SSMP1002A032OutDto ssmp1002a032(SSMP1002A032InDto input)
			throws DefaultApplicationException {

		logger.debug("============== SERVICE START ==============");
		logger.debug("input = {}", input);

		mSmpEmpInfMng01 = DefaultApplicationContext.getBean(mSmpEmpInfMng01, MSmpEmpInfMng01.class);

		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1002A032OutDto output = new SSMP1002A032OutDto();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		List<DSmpEmpTst000Dto> beanInputs = new ArrayList<DSmpEmpTst000Dto>();

		/**
		 * @BXMType Loop
		 * @Desc Mapping input data dto
		 */
		for (SSMP1002A032InDtoSubGrid01 subGrid01 : input.getGrid01()) {

			DSmpEmpTst000Dto beanInput = new DSmpEmpTst000Dto();
			// Generated by code generator [[
			beanInput.setFeduEmpNo(subGrid01.getFeduEmpNo());
			// Generated by code generator ]]

			beanInputs.add(beanInput);
		}

		/**
		 * @BXMType BeanCall
		 * @Desc Call bean method to delete employee informations
		 */
		int removeCnt = mSmpEmpInfMng01.removeEmpInfList(beanInputs);
		logger.debug("removeCnt : {}", removeCnt);

		/**
		 * @BXMType LogicalArea
		 * @Desc output data mapping
		 */
		{
			output.setSuccYn("Y");
		}
		
		/**
		 * @BXMType LogicalArea
		 * @Desc add message
		 */
		{
			DefaultApplicationContext.addMessage("BXMI60000", null, new Object[] { });
		}


		logger.debug("output = {}", output);
		logger.debug("============== SERVICE END ==============");

		return output;
	}

}

