package bxm.dft.smp.online.bean;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import bxm.common.annotaion.BxmCategory;
import bxm.container.annotation.BxmBean;
import bxm.dft.app.DefaultApplicationException;
import bxm.dft.context.DefaultApplicationContext;
import bxm.dft.smp.online.dbio.DSmpEmpTst003;
import bxm.dft.smp.online.dbio.dto.DSmpEmpTst003selectList01Out;
import bxm.dft.smp.online.service.dto.SSMP1006A002SubDto;

/**
 * <b>BXM Bean class</b>
 * <p>
 * <b>Revision history</b><br>
 * <pre>
 * 2017.11.14 : New creation
 * </pre>
 *
 * @since 2017.11.14
 * @version 1.0.0
 * @author Education
 */
@BxmBean
@BxmCategory(logicalName = "Employee Info Management 03", description = "Employee Info Management 03")
public class MSmpEmpInfMng03 {
	private final Logger logger = LoggerFactory.getLogger(this.getClass());

	private DSmpEmpTst003 dSmpEmpTst003;

	@BxmCategory(logicalName = "Multi-Select", description = "Multi-Select")
	public List<SSMP1006A002SubDto> getMultiEmpList(List<SSMP1006A002SubDto> input) throws DefaultApplicationException {
		dSmpEmpTst003 = DefaultApplicationContext.getBean(DSmpEmpTst003.class);
		
		/**
		 * @BXMType VariableDeclaration
		 */
		List<SSMP1006A002SubDto> output = new ArrayList<SSMP1006A002SubDto>();
		
		/**
		 * @BXMType VariableDeclaration
		 */
		SSMP1006A002SubDto beanOut = null;
		
		/**
		 * @BXMType Loop
		 */
		for (SSMP1006A002SubDto subDto : input) {
			/**
			 * @BXMType DbioCall
			 * @Desc select multi employee info.
			 */
			DSmpEmpTst003selectList01Out result = dSmpEmpTst003.selectMultiEmpList(subDto.getFeduEmpNo());

			/**
			 * @BXMType VariableDeclaration
			 */
			beanOut = new SSMP1006A002SubDto();
			
			/**
			 * @BXMType LogicalArea
			 * @Desc Dbio output data mapping
			 */
			{
				// Generated by code generator [[
				beanOut.setFeduEmpNo(result.getFeduEmpNo());
				beanOut.setFeduEmpNm(result.getFeduEmpNm());
				beanOut.setFeduOccpNm(result.getFeduOccpNm());
				beanOut.setFeduMngrEmpNo(result.getFeduMngrEmpNo());
				beanOut.setFeduIpsaDt(result.getFeduIpsaDt());
				beanOut.setFeduPayAmt(result.getFeduPayAmt());
				beanOut.setFeduDeptNo(result.getFeduDeptNo());
				// Generated by code generator ]]
			}
			output.add(beanOut);
		}
		logger.debug("Total Selected Count: [{}]", output.size());
		return output;
	}
}
